### ISSUE TITLE
Importer clears the steps when they are pasted in

### ISSUE THREAD

**Issue by MortenTobiasNielsen** [MortenTobiasNielsen/Factorio-TAS-Generator#232]
I unfortunately haven't been able to pin point why it happens, but it seems to have something to do with either stone furnace or inserter. It works when all steps are transport belt.

**Comment by MortenTobiasNielsen** [comment]
It seems like the component won't allow more lines than can be in the window.

**Comment by theis999** [comment]
![image](https://user-images.githubusercontent.com/18309265/230602986-1cb1351e-2f72-4c9d-8ec0-b96f9857ffca.png)
It is this no-scroll setting that prevents more text than can fit inside the frame. It is easily removed, but it would mean that a scroll bar is present.

Do the imported steps get cleared due to the "clear import" checkbox or something else?

**Comment by MortenTobiasNielsen** [comment]
I was looking for something like that but couldn't find it - nice that you found it. No problem with a scroll bar, if it makes the feature more useable. 

It seems like it is the underlying component, which won't allow it. It also happens when "clear import" is unchecked.

**Comment by theis999** [comment]
It wasn't particularly hard to find, when i had specifically put it on 😎 As i recall it, the options were between always having a scrollbar and never having one. But of course usability shouldn't be sacrificed for aesthetics.

If you know how to trigger it, can you paste the imports here?

**Comment by MortenTobiasNielsen** [comment]
Hehe, yeah that makes it a little easier. 😂 I am not at my computer, but it should at least happen when you record more than 100 steps and try to paste them into the import field.
