### ISSUE TITLE
Warning on change recipe

### ISSUE THREAD

**Issue by theis999** [MortenTobiasNielsen/Factorio-TAS-Generator#245]
When setting a new recipe on an assembler, if it is crafting something it will empty the assembler and cancel the craft. However most of the time you want it to finish crafting that item before switching.
It might even be desirable to block recipe changes before it finalize the craft

**Comment by MortenTobiasNielsen** [comment]
I use Take x amount before I change the recipe to "block" it until the craft is done. There might though be a more elegant way. 

When you get later into a run it won't be possible to align all assembly crafts. In some cases because it would take an unreasonable amount of real world time, but furthermore it might actually be impossible to await every assembler if you want to keep moving - which you almost always want. So I don't really want to get 30 warnings as I run through an assembling hub doing a change from iron gear wheel to e.g. steel furnace.

**Comment by theis999** [comment]
Good point, i was mostly thinking in terms of my steelaxe run. Where every assembler matters and it is possible to be tick perfect on each of them.
Using Take X does work but it also cost you 1 tick. Since setting the recipe clears the inventory in the same tick.

It makes sense to split assemblers in two classes: Personal and Automated. 
- Where the personal assemblers are only handfed and emptied by hand. These makes sense to always get a warning on, as we can assume the user fed them exactly what they wanted.
- Where the automated assemblers are fed by inserters. Here it probably doesn't make sense to have a warning as they will in theory be continually re-fed.

I haven't investigated if it is trivial to find out if an assembler has inserters attached.

It could also make sense to have a more fine masked warning filter

**Comment by MortenTobiasNielsen** [comment]
It is hand-fed assemblers I am talking about. I have around 50 assemblers bundled together in a cluster and it simply isn't always possible to tick-perfect every single assembler when you have a few seconds of walk time and have to change a large amount of the assemblers - at the very least I simply don't want to use multiple hours doing so - especially given that it often lead to incredibly frustrating misalignments where a single tick completely fucks up your run  and you can spend days trying to fix it. This might make sense in a steel-axe run where every tick matters, but in an any% you could spend the rest of tour life on the run and still not be done, if you want to do everything tick perfect. :)
